mode: "sweep" # Wähle: "single", "grid" oder "sweep"

single_run:
  lookback: 96
  horizon: 24
  batch_size: 32
  epochs: 250
  hidden_size: 64
  num_layers: 2
  patience: 15

grid_options:
  lookback: [48, 96]
  horizon: [12, 24]
  batch_size: [16, 32]
  epochs: [100, 250]
  hidden_size: [32, 64]
  num_layers: [1, 2]

sweep_config:
  method: bayes
  metric:
    name: val_loss
    goal: minimize
  parameters:
    lookback:
      values: [48, 96]
    horizon:
      values: [12, 24]
    batch_size:
      values: [16, 32]
    hidden_size:
      values: [32, 64]
    num_layers:
      values: [1, 2]
    epochs:
      value: 100
    patience:
      value: 15
