_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 51
                - 55
            "2":
                - 1
                - 51
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.5
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
        visualize:
            Ground Truth Line:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: Index
                        "y": Ground Truth
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: Ground Truth
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Ground Truth Line_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            Predictions vs Ground Truth:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: Index
                        "y": Prediction
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: Predictions
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Predictions vs Ground Truth_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 32
epochs:
    value: 250
horizon:
    value: 24
learning_rate:
    value: 0.001
lookback:
    value: 96
